(()=>{
'use strict';
const SESSION_KEY='radar-session',MASTER_KEY='garimpeiro-master-results',CATEGORY_KEY='garimpeiro-category-filter',SUPPLIER_KEY='garimpeiro-supplier-filter';
const $=id=>document.getElementById(id),N=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim();let busy=false;
const read=(k,f=null)=>{try{return JSON.parse(localStorage.getItem(k)||'null')??f}catch{return f}},write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const resultKey=r=>`${N(r?.product?.supplier)}::${N(r?.product?.id)}::${N(r?.product?.link)}::${N(r?.product?.name)}`;
const session=()=>read(SESSION_KEY,null),master=()=>read(MASTER_KEY,[])||[];
function mergeIntoMaster(results){if(!Array.isArray(results)||!results.length)return;const cur=master();if(!cur.length){write(MASTER_KEY,results);return}const map=new Map(cur.map(r=>[resultKey(r),r]));results.forEach(r=>map.set(resultKey(r),r));write(MASTER_KEY,[...map.values()])}
function currentFilter(){return{category:$('categoryFilter')?.value||localStorage.getItem(CATEGORY_KEY)||'all',supplier:$('supplierFilter')?.value||localStorage.getItem(SUPPLIER_KEY)||'all'}}
function capture(){const s=session();if(!s?.results?.length)return;const f=currentFilter(),outside=s.results.some(r=>(f.category!=='all'&&N(r?.product?.category)!==N(f.category))||(f.supplier!=='all'&&N(r?.product?.supplier)!==N(f.supplier)));if((f.category==='all'&&f.supplier==='all')||outside)write(MASTER_KEY,s.results);else mergeIntoMaster(s.results)}
function source(){const m=master();return m.length?m:(session()?.results||[])}
function values(field){return[...new Set(source().map(r=>String(r?.product?.[field]||'').trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'pt-BR',{sensitivity:'base'}))}
function esc(s){return String(s).replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;')}
function populateSelect(id,items,allLabel,key){const sel=$(id);if(!sel)return;const wanted=sel.value||localStorage.getItem(key)||'all',sig=items.join('|');if(sel.dataset.signature===sig)return;sel.dataset.signature=sig;sel.innerHTML=`<option value="all">${allLabel}</option>`+items.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');sel.value=items.includes(wanted)?wanted:'all'}
function populate(){populateSelect('categoryFilter',values('category'),'Todas as categorias',CATEGORY_KEY);populateSelect('supplierFilter',values('supplier'),'Todos os fornecedores',SUPPLIER_KEY)}
function restoreApp(){$('btnRestore')?.click()}
function apply({remember=true}={}){if(busy)return;busy=true;try{const s=session();if(!s||!Array.isArray(s.results))return;let full=master();if(!full.length){full=s.results;write(MASTER_KEY,full)}const f=currentFilter();if(remember){f.category==='all'?localStorage.removeItem(CATEGORY_KEY):localStorage.setItem(CATEGORY_KEY,f.category);f.supplier==='all'?localStorage.removeItem(SUPPLIER_KEY):localStorage.setItem(SUPPLIER_KEY,f.supplier)}s.results=full.filter(r=>(f.category==='all'||N(r?.product?.category)===N(f.category))&&(f.supplier==='all'||N(r?.product?.supplier)===N(f.supplier)));write(SESSION_KEY,s);restoreApp();setTimeout(()=>{const cap=$('resultsCaption'),bits=[];if(f.supplier!=='all')bits.push(`Fornecedor: ${f.supplier}`);if(f.category!=='all')bits.push(`Categoria: ${f.category}`);if(cap&&bits.length)cap.textContent+=` · ${bits.join(' · ')}`},35)}finally{setTimeout(()=>busy=false,70)}}
function init(){const cat=$('categoryFilter'),sup=$('supplierFilter'),body=$('resultsBody');if(!cat||!sup||!body)return;capture();populate();const savedCat=localStorage.getItem(CATEGORY_KEY)||'all',savedSup=localStorage.getItem(SUPPLIER_KEY)||'all';cat.value=[...cat.options].some(o=>o.value===savedCat)?savedCat:'all';sup.value=[...sup.options].some(o=>o.value===savedSup)?savedSup:'all';if(cat.value!=='all'||sup.value!=='all')apply({remember:false});cat.addEventListener('change',()=>apply());sup.addEventListener('change',()=>apply());new MutationObserver(()=>{if(busy)return;const s=session();if(!s?.results?.length){populate();return}const f=currentFilter(),outside=s.results.some(r=>(f.category!=='all'&&N(r?.product?.category)!==N(f.category))||(f.supplier!=='all'&&N(r?.product?.supplier)!==N(f.supplier)));if((f.category==='all'&&f.supplier==='all')||outside){write(MASTER_KEY,s.results);populate();if(f.category!=='all'||f.supplier!=='all')setTimeout(()=>apply({remember:false}),0)}else{mergeIntoMaster(s.results);populate()}}).observe(body,{childList:true,subtree:false});$('btnClear')?.addEventListener('click',()=>setTimeout(()=>{if(!localStorage.getItem(SESSION_KEY)){[MASTER_KEY,CATEGORY_KEY,SUPPLIER_KEY].forEach(k=>localStorage.removeItem(k));cat.dataset.signature=sup.dataset.signature='';populate();cat.value=sup.value='all'}},120))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
