(()=>{'use strict';
const SESSION='radar-session',MASTER='garimpeiro-master-results',$=id=>document.getElementById(id),N=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim(),T=s=>N(s).split(' ').filter(x=>x.length>1&&!['de','da','do','dos','das','para','com','sem','e','em','a','o','kit','unidade','unidades'].includes(x)),PN=v=>Number(String(v??0).replace(',','.').replace(/[^0-9.-]/g,''))||0,read=(k,f=null)=>{try{return JSON.parse(localStorage.getItem(k)||'null')??f}catch{return f}},write=(k,v)=>localStorage.setItem(k,JSON.stringify(v)),clone=v=>JSON.parse(JSON.stringify(v)),session=()=>read(SESSION,{luiz:[],shop:[],results:[]})||{luiz:[],shop:[],results:[]},pkey=p=>`${N(p?.supplier)}::${N(p?.sku)}::${N(p?.link)}::${N(p?.name)}`,rkey=r=>pkey(r?.product||{});
function cat(raw){const o=String(raw||'').trim();if(!o)return'';const generic=new Set(['diversos','diverso','outros','outro','geral','gerais','categoria','categorias','departamento','departamentos','variados','variado']);let p=o.split(/\s*(?:>|»|→|\||\\|\/|::)\s*/).map(x=>x.trim()).filter(Boolean);if(p.length>1)p=p.filter(x=>!generic.has(N(x)));let v=p[p.length-1]||o,n=N(v),a={ferramenta:'FERRAMENTAS',ferramentas:'FERRAMENTAS',audio:'ÁUDIO',audios:'ÁUDIO',cabo:'CABOS',cabos:'CABOS',adaptador:'ADAPTADORES',adaptadores:'ADAPTADORES',carregador:'CARREGADORES',carregadores:'CARREGADORES'};return a[n]||v.replace(/\s+/g,' ').toUpperCase()}
function cp(p){if(!p)return p;const c=cat(p.category);return c&&c!==p.category?{...p,categoryOriginal:p.categoryOriginal||p.category,category:c}:p}
function normalize(){const s=session(),list=(s.luiz||[]).map(cp),by=new Map(list.map(p=>[pkey(p),p])),fix=r=>({...r,product:by.get(pkey(r.product))||cp(r.product)});s.luiz=list;s.results=(s.results||[]).map(fix);write(SESSION,s);const m=read(MASTER,[])||[];if(m.length)write(MASTER,m.map(fix));localStorage.removeItem('garimpeiro-category-filter')}
function adcats(a){const s=new Set(),add=x=>{const c=cat(x);if(c)s.add(N(c))};add(a.category);String(a.related||'').split(/[;,]+/).forEach(x=>{add(x);x.split(/\s*(?:>|»|→|\||\\|\/|::)\s*/).forEach(add)});return s}
function sim(p,a){const A=T(p.name),B=T(a.name),sb=new Set(B),inter=A.filter(x=>sb.has(x)).length,uni=new Set([...A,...B]).size,imp=A.filter(x=>/\d/.test(x)||x.length>=5),ih=imp.filter(x=>sb.has(x)).length/Math.max(1,imp.length),nums=A.filter(x=>/\d/.test(x)),nh=nums.length?nums.filter(x=>sb.has(x)).length/nums.length:.5,pc=N(cat(p.category)),cs=adcats(a);let cb=pc&&cs.has(pc)?1:0;if(!cb&&pc)for(const c of cs)if(c.includes(pc)||pc.includes(c)){cb=.75;break}let z=inter/Math.max(1,uni)*.5+ih*.23+nh*.17+cb*.1;if(N(p.name).length>8&&(N(p.name).includes(N(a.name))||N(a.name).includes(N(p.name))))z+=.1;return Math.min(1,z)}
function pack(s){const n=N(s),m=n.match(/\b(?:kit|pack|conjunto)(?: com)?\s*(\d+)\b|\b(\d+)\s*(?:unidades|unid|pecas|pcs)\b/);if(m)return'kit';return /\bkit\b|\bpack\b|\bconjunto\b/.test(n)?'kit':'unit'}
function market(m){const u=m.filter(x=>pack(x.name)==='unit'),k=m.filter(x=>pack(x.name)==='kit'),base=u.length?u:m;if(!base.length)return null;let a=[...base].sort((x,y)=>x.price-y.price);if(a.length>=8){const ps=a.map(x=>x.price),q=p=>ps[Math.floor((ps.length-1)*p)],iq=q(.75)-q(.25),lo=q(.25)-1.5*iq,hi=q(.75)+1.5*iq,b=a.filter(x=>x.price>=lo&&x.price<=hi);if(b.length>=3)a=b}const ps=a.map(x=>x.price),min=a[0],max=a[a.length-1],mean=ps.reduce((x,y)=>x+y,0)/ps.length,median=ps.length%2?ps[(ps.length-1)/2]:(ps[ps.length/2-1]+ps[ps.length/2])/2;return{min:min.price,max:max.price,mean,median,minSold:min.sold||0,maxSold:max.sold||0,totalSold:a.reduce((x,y)=>x+(y.sold||0),0),unitCount:u.length,kitCount:k.length,all:m}}
function query(p,b){const bt=T(b?.name||''),sh=T(p.name).filter(x=>bt.includes(x)),nu=T(p.name).filter(x=>/\d/.test(x));return[...new Set([...sh,...nu])].slice(0,8).join(' ')||p.name}
let busy=false;
async function analyze(){if(busy)return;normalize();let s=session(),products=s.luiz||[],ads=s.shop||[];if(!products.length||!ads.length)return alert('Importe pelo menos um fornecedor e a planilha da Shopee.');busy=true;const b=$('btnAnalyze'),bar=$('progressBar'),text=$('progressText');$('progressWrap')?.classList.remove('hidden');if(b)b.disabled=true;const threshold=Math.max(.4,PN($('matchThreshold')?.value||70)/100),old=read(MASTER,[])||[],ai=new Map();old.forEach(r=>{if(r?.aiScreenshot||r?.market?.source==='ai-screenshot')ai.set(rkey(r),clone(r))});const out=[];try{for(let i=0;i<products.length;i++){const p=cp(products[i]),pc=N(p.category),pool=ads.filter(a=>{const cs=adcats(a);return pc&&[...cs].some(c=>c===pc||c.includes(pc)||pc.includes(c))}),src=pool.length>=3?pool:ads,sc=[];for(const ad of src){const score=sim(p,ad);if(score>=Math.max(.43,threshold-.2))sc.push({...ad,score})}sc.sort((x,y)=>y.score-x.score);if((sc[0]?.score||0)>=threshold){const rel=sc.filter(x=>x.score>=Math.max(threshold-.06,sc[0].score-.2)).slice(0,80),mk=market(rel);if(mk){let r={product:p,score:sc[0].score,market:mk,query:query(p,sc[0])},prev=ai.get(rkey(r));if(prev){r.marketBeforeAI=clone(mk);r.market=clone(prev.market);r.aiScreenshot=clone(prev.aiScreenshot)}out.push(r)}}if(i%15===0||i===products.length-1){if(bar)bar.style.width=`${Math.round((i+1)/products.length*100)}%`;if(text)text.textContent=`Garim analisando ${i+1} de ${products.length} · ${out.length} oportunidades`;await new Promise(r=>setTimeout(r,0))}}s=session();s.luiz=(s.luiz||[]).map(cp);s.results=out;write(SESSION,s);write(MASTER,out);localStorage.removeItem('garimpeiro-category-filter');localStorage.removeItem('garimpeiro-supplier-filter');if(text)text.textContent=`Concluído: ${out.length} oportunidades em ${new Set(products.map(p=>p.supplier||'Sem fornecedor')).size} fornecedores.`;if(bar)bar.style.width='100%';$('btnRestore')?.click()}catch(e){alert(e.message)}finally{busy=false;if(b)b.disabled=false}}
function hook(){const b=$('btnAnalyze');if(b){b.onclick=analyze;b.title='Compara a Shopee com todos os fornecedores importados'}}
function init(){normalize();hook();setInterval(()=>{normalize();hook()},1800)}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init,{once:true}):init();
})();